root: true

env:
  browser: true
  es2021: true
  node: true
  jest: true

globals:
  JSX: true

extends: ['plugin:react/recommended', 'airbnb']
plugins: ['react', '@typescript-eslint']

settings:
  import/resolver:
    node:
      moduleDirectory: ['./node_modules', './src']
      extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.sass', '.scss']

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true

rules:
  arrow-body-style: 0
  arrow-parens: 0
  comma-dangle: 0
  dot-notation: 0
  import/extensions: 0
  import/no-absolute-path: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/prefer-default-export: 0
  jsx-quotes: ['error', 'prefer-single']
  max-classes-per-file: 0
  no-bitwise: 0
  no-empty-function: 0
  no-nested-ternary: 0
  no-plusplus: 0
  no-shadow: 0
  no-unused-vars: 0
  no-use-before-define: 0
  no-useless-constructor: 0
  object-curly-newline:
    ['error', { 'ImportDeclaration': 'never', 'ExportDeclaration': 'never' }]
  prefer-destructuring: 0
  react/destructuring-assignment: 0
  react/jsx-filename-extension: [2, extensions: ['.js', '.jsx', '.ts', 'tsx']]
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/require-default-props: 0
  '@typescript-eslint/no-shadow': error
