/**
 * Encapsulation for reusable styles variables.
 */
export default {
  colorBackgroundBadge: '#dde0ee',
  colorBackgroundReviewBadge: '#c1eeed',
  colorBackgroundRect: '#e9edfb',
  colorForegroundPickMain: '#4f69ca',
  colorForegroundPickAux1: '#33c7ba',
  footerHeight: '17.5rem',
  greetingsViewContentActionGroupWidth: '38rem',
  greetingsViewHeadEdgeElemsWidthBase: '15rem',
  greetingsViewHeadPaddingHorizontal: '16rem',
  inputBorderRadiusDefault: '.6rem',
  inputHeightDefault: '3.072rem',
  logoRectHeightBase: '2.625rem',
  opacityButtonHover: '.8',
  opacityButtonActive: '.5',
  opacityButtonIdleInversed: '.8',
  profilePhotoWrapperWidth: '20rem',
  searchInputWidth: '65rem',
  sectionShadow: 'drop-shadow(1rem 1rem .6rem rgba(0, 0, 0, .1))',
  thiknessDefault: '0.078vw',
  widthLoginButton: '20rem',
  widthMotivatorBadge: '25rem',
  widthOffsetProfileBadge: '10rem',
  widthReviewCard: '67.38em',
  zIndexDimmedContent: '801',
  zIndexDimmingWrapper: '800',
  zIndexLoginBadge: '50',
  zIndexPopupCookie: '100',
  zIndexPopupExpandView: '100',
  zIndexPopupLogin: '100',
  zIndexPopupSearch: '100',
  zIndexSelectMenu: '150',
  zIndexSelectMenuLayer2: '200',
  zIndexScrollButton: '200',
  zIndexPageLoader: '900'
};
