root: true

env:
  browser: true
  es6: true
  node: true

extends: 'airbnb-base'

settings:
  import/resolver:
    typescript: {}

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins: ['@typescript-eslint']

rules:
  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle: 0
  dot-notation: 0
  import/extensions: 0
  import/no-absolute-path: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/prefer-default-export: 0
  max-classes-per-file: 0
  no-empty-function: 0
  no-console: 0
  no-nested-ternary: 0
  no-param-reassign: ['error', { 'props': false }]
  no-shadow: 0
  no-use-before-define: 0
  no-useless-constructor: 0
  no-underscore-dangle: 0
  no-unused-vars: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  radix: 0
  '@typescript-eslint/no-shadow': error
